### ISSUE TITLE
Payroll Taxes not reflected in tiers

### ISSUE THREAD

**Issue by justinbarak** [iethree/my-tax-plan#14]
2 thoughts about payroll taxes. 

1. If you take different taxes at different thresholds, it's odd to see the base "cumulative total revenue" not change at different amounts. For example, setting all rate taxes to 0% shows a flat $768B as the cumulative total revenue. I would think this should increase along the different income thresholds so that the base revenue is shown incrementally as well.
2. Right now you can set 100% tax rate in the graph, but in theory this is incremental to Payroll taxes, so it's possible to be taxed >100%. Maybe just ignore numbers that when combined with Payroll taxes would be >100%.

Other curious thing I noticed, was that at 100% taxes a single $20k/yr person was only taxed at 50%. Is this due to the standard deduction?

**Comment by iethree** [comment]
Very good points. My thinking was the payroll + capital gains taxes were details that most people would not want to dig into, but I now see that hiding some of that complexity actually obscures what goes into total tax revenue.

The discrepancy with 100% tax rates is a combination of deductions and credits. My simulation doesn't actually apply specific deductions, it uses aggregate data to assign an average amount of credits and deductions for taxpayers in each bracket. This is not a good predictor of what any individual's taxes will be, but it is a fairly accurate simulation of the tax burden on various classes of taxpayers.
